Title: DataCamp exercises (Week 3)
Author: Dr. Glasbrenner
Date: 2018-09-16 23:59
Tags: module-exercise
Slug: datacamp-exercises-week-3
Show_summary: false
Show_link: false

## Instructions

You should have received an invitation in your Mason email address to register and join [DataCamp][datacamp-url].
If you have not done so already, complete the registration so that you can join the *Introduction to Computational and Data Sciences* class there.
You are to watch the tutorial videos and complete the interactive coding challenges from the following lessons, which will let you practice and supplement this week's content.

::::: {.callout .secondary}
[Important!]{.h3}

Your progress through these lessons is being tracked and completing them counts towards the *Module exercises* category of your grade. 
:::::

[From *Introduction to R*]{.h4}

*   Intro to basics

*   Vectors

[From *Reporting with R Markdown*]{.h4}

*  Authoring R Markdown reports

*  Embedding Code

[From *Working with the RStudio IDE Part 1*]{.h4}

*   Orientation

[From *Working with the RStudio IDE Part 2*]{.h4}

*   Version Control

[datacamp-url]: https://datacamp.com
